import { notFound } from "next/navigation";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

export default async function PublicSitePage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;

  // slug is the business ID — find the generated site
  const business = await db.business.findUnique({
    where: { id: slug },
    include: { site: true },
  });

  // Publish-status gate: only published/live sites are publicly reachable.
  // Drafts are previewable by the owner via /dashboard/[id]/preview.
  const LIVE_STATUSES = new Set(["live", "published"]);
  if (!business?.site || !LIVE_STATUSES.has(business.site.status)) {
    notFound();
  }

  const { html, css, meta } = business.site;

  const title = meta ? (JSON.parse(meta) as { title?: string }).title ?? business.name : business.name;
  const description = meta
    ? (JSON.parse(meta) as { description?: string }).description
    : null;

  const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(title)}</title>
  ${description ? `<meta name="description" content="${escapeHtml(description)}" />` : ""}
  <style>${css}</style>
  <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><text y='28' font-size='28'>🌐</text></svg>" />
</head>
<body>
  ${html}
  <script>
    // Bizweave public site — generated with love by AI agents
    console.log("Powered by Bizweave — ${escapeHtml(business.name)}");
  </script>
</body>
</html>`;

  return (
    <div className="min-h-screen">
      {/* Bizweave attribution bar with link to dashboard */}
      <div className="fixed bottom-0 left-0 right-0 z-50 flex items-center justify-center gap-2 border-t border-white/10 bg-[#0a0b0f]/90 py-2 text-[10px] uppercase tracking-wider backdrop-blur-sm">
        <span className="text-text-muted">Generated by</span>
        <a
          href={process.env.NEXT_PUBLIC_APP_URL ?? "/"}
          className="font-semibold text-accent-primary hover:underline"
          target="_blank"
          rel="noopener noreferrer"
        >
          Bizweave
        </a>
      </div>
      <iframe
        srcDoc={fullHtml}
        className="h-[calc(100vh-32px)] w-full border-0"
        title={title}
        sandbox="allow-scripts allow-same-origin"
      />
    </div>
  );
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
